// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdlhxsacrnjfcbcwougw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbGh4c2Fjcm5qZmNiY3dvdWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTM2NDIsImV4cCI6MjA2Nzk4OTY0Mn0.ZMC4d4LACiPwdER97pAQDjhbH6tZThXbXqf36zPjeH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});